# Generated by Django 3.2.8 on 2021-10-12 02:26

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('AplicacionCiclo3', '0002_rename_idregistroventas_registroventas_id'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='registroventas',
            name='idAdministrador',
        ),
        migrations.RemoveField(
            model_name='registroventas',
            name='idCliente',
        ),
    ]
