# Generated by Django 3.2.8 on 2021-10-14 21:48

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('AplicacionCiclo3', '0002_producto_precio'),
    ]

    operations = [
        migrations.AlterField(
            model_name='producto',
            name='bateria',
            field=models.BooleanField(default=False),
        ),
        migrations.AlterField(
            model_name='producto',
            name='software_incluido',
            field=models.CharField(max_length=30),
        ),
    ]
