# Generated by Django 3.2.8 on 2021-10-21 19:37

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('AplicacionCiclo3', '0003_auto_20211014_1648'),
    ]

    operations = [
        migrations.AddField(
            model_name='registroventas',
            name='cantidad',
            field=models.IntegerField(default=0),
        ),
        migrations.AddField(
            model_name='registroventas',
            name='idProducto',
            field=models.ForeignKey(null=True, on_delete=django.db.models.deletion.CASCADE, to='AplicacionCiclo3.producto'),
        ),
    ]
