# Generated by Django 3.2.8 on 2021-10-12 02:35

from django.conf import settings
from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('AplicacionCiclo3', '0003_auto_20211011_2126'),
    ]

    operations = [
        migrations.AddField(
            model_name='registroventas',
            name='idAdministrador',
            field=models.ForeignKey(null=True, on_delete=django.db.models.deletion.CASCADE, related_name='registro_ventas', to=settings.AUTH_USER_MODEL),
        ),
        migrations.AddField(
            model_name='registroventas',
            name='idCliente',
            field=models.ForeignKey(null=True, on_delete=django.db.models.deletion.CASCADE, to='AplicacionCiclo3.cliente'),
        ),
    ]
