# Generated by Django 3.2.8 on 2021-10-13 00:24

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('AplicacionCiclo3', '0004_auto_20211011_2135'),
    ]

    operations = [
        migrations.RenameField(
            model_name='comentarios',
            old_name='idComentario',
            new_name='id',
        ),
    ]
