from .account import Account
from .user import User
from .producto import Producto
from .proveedores import Proveedores
from .cliente import Cliente
from .registro_ventas import RegistroVentas
from .proveedorProducto import ProveedorProductos
from .ventasProductos import VentasProductos
from .comentarios import Comentarios