from .accountSerializers import AccountSerializer
from .userSerializers import UserSerializers
from .clienteSerializers import ClienteSerializer
from .comentariosSerializers import ComentariosSerializers
from .productoSerializers import ProductoSerializers
from .proveedoresSerializers import ProveedoresSerializers
from .registro_ventasSerializers import RegistroVentasSerializers